name: Release dot_ios_sdk_spm

on:
  repository_dispatch:
    types: dot_ios_sdk_spm_release
jobs:
  release:
    name: Release dot_ios_sdk_spm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Release dot-ios-sdk-spm
        run: |
          ../../prepare_swift_package.sh --release_version=$RELEASE_VERSION
        env: 
          RELEASE_VERSION: "${{github.event.client_payload.release_version}}"
          
      
      - name: Push changes
        run: |
          git config --global user.name 'Jakub Vallo'
          git config --global user.email 'jakub.vallo@innovatrics.com'
          git add *
          git commit -m "[dot_ios_sdk_spm_release workflow] release DOT iOS SDK Swift Package Manager $RELEASE_VERSION"
          git push
        env:
          RELEASE_VERSION: "${{github.event.client_payload.release_version}}"
